target 'AdaptiveCards' do
  project './AdaptiveCards/AdaptiveCards.xcodeproj'
end

target 'ADCIOSVisualizer' do
  project './ADCIOSVisualizer/ADCIOSVisualizer.xcodeproj'
end

workspace 'AdaptiveCards'
platform :ios, '13'
