target 'AdaptiveCards' do
  use_frameworks!
  pod 'MicrosoftFluentUI', '0.1.9'
  project './AdaptiveCards/AdaptiveCards.xcodeproj'
end

target 'ADCIOSVisualizer' do
  use_frameworks!
  pod 'MicrosoftFluentUI', '0.1.9'
  project './ADCIOSVisualizer/ADCIOSVisualizer.xcodeproj'
end

workspace 'AdaptiveCards'
platform :ios, '13'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
            config.build_settings['PROVISIONING_PROFILE'] = ""
            config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ""
        end
    end
end

